/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SeedImport } from './routes/seed'
import { Route as LiveImport } from './routes/live'
import { Route as DevImport } from './routes/dev'
import { Route as ApprovalsImport } from './routes/approvals'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SeedRoute = SeedImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRoute,
} as any)

const LiveRoute = LiveImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRoute,
} as any)

const DevRoute = DevImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRoute,
} as any)

const ApprovalsRoute = ApprovalsImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsImport
      parentRoute: typeof rootRoute
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevImport
      parentRoute: typeof rootRoute
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveImport
      parentRoute: typeof rootRoute
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/dev': typeof DevRoute
  '/live': typeof LiveRoute
  '/seed': typeof SeedRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/dev': typeof DevRoute
  '/live': typeof LiveRoute
  '/seed': typeof SeedRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/dev': typeof DevRoute
  '/live': typeof LiveRoute
  '/seed': typeof SeedRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/approvals' | '/dev' | '/live' | '/seed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/approvals' | '/dev' | '/live' | '/seed'
  id: '__root__' | '/' | '/approvals' | '/dev' | '/live' | '/seed'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DevRoute: typeof DevRoute
  LiveRoute: typeof LiveRoute
  SeedRoute: typeof SeedRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  DevRoute: DevRoute,
  LiveRoute: LiveRoute,
  SeedRoute: SeedRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/approvals",
        "/dev",
        "/live",
        "/seed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/approvals": {
      "filePath": "approvals.tsx"
    },
    "/dev": {
      "filePath": "dev.tsx"
    },
    "/live": {
      "filePath": "live.tsx"
    },
    "/seed": {
      "filePath": "seed.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
